# AUTHOR: Eric Lauret
# DESCRIPTION: First custom image to run a simple .NET Core console app

FROM mcr.microsoft.com/dotnet/core/runtime:3.1

COPY FirstCoreDockerApp/bin/Release/netcoreapp3.1/publish/ app/

ENTRYPOINT [ "dotnet", "app/FirstCoreDockerApp.dll" ]